spring:
  profiles:
    include:
      - jwt

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/murator
    username: root
    password: 1234

domain:
  host: 'localhost'