server:

  port: 9090
  ssl:
    enabled: true
    key-store-password: somepass
    key-store: classpath:keystore.p12
    key-store-type: PKCS12

spring:

  profiles:
    include:
      - cors
      - jwt
      - openapi

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/murator
    username: root
    password: 1234

domain:
  host: 'localhost'